kind = "web"
previewPath = "/"
title = "Tracker Loc ID"
version = "1.0.0"
id = "artifacts/tracker-loc"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25091

[services.development]
run = "pnpm --filter @workspace/tracker-loc run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/tracker-loc", "run", "build" ]
publicDir = "artifacts/tracker-loc/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25091"
BASE_PATH = "/"
